os:
    - linux
    - windows

language: python
python:
    - 2.7
    - 3.4

install:
    - python setup.py install
    - pip install coveralls

script:
    - nosetests --cover-package=dota2crawler --with-coverage

after_success:
    coveralls
